# Bridge to AWS IoT
connection aws-iot
address a75p0fsmm0h6r-ats.iot.us-east-1.amazonaws.com:443
bridge_alpn x-amzn-mqtt-ca
bridge_cafile /etc/mosquitto/certs/ca.pem
bridge_certfile /etc/mosquitto/certs/certificate.pem
bridge_keyfile /etc/mosquitto/certs/private.key
bridge_insecure false
cleansession false
start_type automatic
notifications false
keepalive_interval 60
# AWS IoT thing name
remote_clientid DEVICE_ID
# AWS IoT Jobs topics
topic $aws/things/DEVICE_ID/jobs/notify in 1
topic $aws/things/DEVICE_ID/jobs/get out 1
topic $aws/things/DEVICE_ID/jobs/get/accepted in 1
topic $aws/things/DEVICE_ID/jobs/get/rejected in 1
topic $aws/things/DEVICE_ID/jobs/+/get out 1
topic $aws/things/DEVICE_ID/jobs/+/get/accepted in 1
topic $aws/things/DEVICE_ID/jobs/+/update out 1
# Outbound topic which sends events
topic eatabit/things/DEVICE_ID/events out 1

# local topics should not be listed here